create or replace TABLE SPOTIFY.DBO.SPOTIFY_ALBUM (
	ALBUM_ID VARCHAR(255) COLLATE 'en-ci',
	ALBUM_NAME VARCHAR(255) COLLATE 'en-ci',
	RELEASE_DATE TIMESTAMP_NTZ(9),
	TOTAL_TRACKS NUMBER(38,0),
	URLS VARCHAR(255) COLLATE 'en-ci',
	SOURCEFILENAME VARCHAR(255) COLLATE 'en-ci',
	SOURCEFILEDATE TIMESTAMP_NTZ(9),
    created_date timestamp_ntz(9)

);